import assert from 'node:assert/strict';
import test from 'node:test';
import { auditAsarEntries } from './asar-hygiene.mjs';

/** What a healthy production package looks like, trimmed to the parts we judge. */
const CLEAN = [
  'package.json',
  'config.example.json',
  'dist/index.js',
  'dist/index.js.map',
  'electron/preload.cjs',
  'gui-design/index.html',
  'gui-design/dist/app.js',
  'gui-design/dist/app.css',
];

test('a clean package passes and says the renderer is there', () => {
  const { errors, notes } = auditAsarEntries(CLEAN);
  assert.deepEqual(errors, []);
  assert.ok(notes.some((note) => note.includes('renderer entry')), notes.join('\n'));
});

test('a missing renderer entry fails — every other check passes on a blank window', () => {
  for (const missing of ['gui-design/index.html', 'gui-design/dist/app.js', 'gui-design/dist/app.css']) {
    const { errors } = auditAsarEntries(CLEAN.filter((entry) => entry !== missing));
    assert.equal(errors.length, 1, `${missing} must be required`);
    assert.match(errors[0], /missing the renderer/);
    assert.ok(errors[0].includes(missing), errors[0]);
  }
});

test('renderer sourcemaps left by dev:renderer are rejected', () => {
  const { errors } = auditAsarEntries([...CLEAN, 'gui-design/dist/app.js.map', 'gui-design/dist/app.css.map']);
  assert.equal(errors.length, 1);
  assert.match(errors[0], /renderer sourcemaps/);
  assert.ok(errors[0].includes('gui-design/dist/app.js.map'), errors[0]);
});

test('renderer sources are rejected', () => {
  const { errors } = auditAsarEntries([...CLEAN, 'gui-design/src', 'gui-design/src/main.tsx']);
  assert.equal(errors.length, 1);
  assert.match(errors[0], /renderer sources/);
});

test('the test suite and the dev fake backend stay banned', () => {
  const { errors } = auditAsarEntries([
    ...CLEAN,
    'gui-design/tests/e2e.mjs',
    'dist/electron/devFakeBackend.js',
    'dist/electron/devFakeBackend.js.map',
  ]);
  assert.equal(errors.length, 2, errors.join('\n'));
  assert.ok(errors.some((error) => error.includes('test suite')), errors.join('\n'));
  assert.ok(errors.some((error) => error.includes('dev fake backend')), errors.join('\n'));
});

test('main-process sourcemaps are deliberately still allowed', () => {
  // Only the renderer tree is swept: dist/**/*.map is what makes a packaged
  // stack trace readable, and it is generated by the same build every time.
  const { errors } = auditAsarEntries([...CLEAN, 'dist/electron/main.js.map']);
  assert.deepEqual(errors, []);
});
